server:
  port: 80
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:~/DBFile/dbf;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;AUTO_RECONNECT=TRUE;DB_CLOSE_ON_EXIT=FALSE #当前用户目录，文件前缀为dbf
    driver-class-name: org.h2.Driver
security:
  ignored:
  - "*.bundle.*"
mail:
  server:
    host: smtp.163.com
    port: 25
    username:   #发件人邮箱名
    password:   #发件人邮箱授权码
  send:
    url:  #域名或ip地址
    from:   #发件人地址
default:
  admin:
    username: root
    password: root
    email: root@root.com
